name: Continuous Heartbeat

on:
  workflow_dispatch:  # Manual trigger

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    
    steps:
    - name: Continuous heartbeat loop
      run: |
        echo "Starting continuous heartbeat service at $(date)"
        for i in {1..30}; do
          echo "Sending heartbeat $i at $(date)"
          curl -s -X GET https://api.kmt.ltd/api/Auth/heartbeat
          echo " - Heartbeat $i completed"
          sleep 120  # Wait 2 minutes between heartbeats
        done
        echo "Continuous heartbeat service completed at $(date)"
