name: Heartbeat Service

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send heartbeat request
      run: |
        echo "Starting heartbeat at $(date)"
        curl -v -X GET https://api.kmt.ltd/api/Auth/heartbeat
        echo "Heartbeat completed at $(date)"
        
    - name: Debug information
      run: |
        echo "GitHub Actions runner information:"
        echo "OS: $(uname -a)"
        echo "Current directory: $(pwd)"
        echo "Environment variables:"
        env
