name: Heartbeat Service

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '*/1 * * * *'  # Run every minute (GitHub doesn't support seconds)

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send heartbeat request
      run: |
        curl -X GET https://api.kmt.ltd/api/Auth/heartbeat
        echo "Heartbeat sent at $(date)"
