name: Test Workflow

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test step
      run: |
        echo "This is a test workflow"
        echo "Current time is $(date)"
